package com.gs.rules.engine.rules

declare IeTicketDistributePojo
    robot_sn: String  //机器sn
    ticket_desc: String //工单描述
    ticket_category: String //工单分类
    guarantees: String //保内保外
    charge_type: String //工时收费
    serve_type: String //现场处理
    kafka_key: String //推送服务
    incident_desc: String //故障描述
    fae: String //fae
    robot_abnormal_score: Double //年龄
    daily_active_score: Double // 开始日期
    distribute_score: Double // 结束日期
    daily_7_view: String //T7日活
    daily_6_view: String //T6日活
    daily_5_view: String //T5日活
    daily_4_view: String //T4日活
    daily_3_view: String //T3日活
    daily_2_view: String //T2日活
    daily_1_view: String //T1日活
    openning_ticket_cnt: Long //未关闭的工单数量
    customer_grade: String //客户等级
    robot_name: String //机器人名
    terminal_user_name: String //终端客户名
    terminal_user_group_name: String //终端客户组名,
    group_customer_grade: String //客户组等级
    robot_faimly_code: String //机器型号
    scene: String //场景
    business_area: String //运维大区
    province: String //所属省
    city: String  //所属城市
    county: String //所属区
    country: String //所属国家
    delivery_date: java.time.LocalDate //交付日期
    status: String //状态
    distribute: Boolean //是否需要推送
    pt: String //分区
end

rule "rule1"
    when
        $pojo : IeTicketDistributePojo(distribute_score > 60 && status == '已交付-正常使用')
    then
        $pojo.setDistribute(true);
end