package com.gs.rules.engine.rules

declare TestPojo
    id: String  // id
    name: String // 名字
    start_day: String // 开始日期
    end_day: String // 结束日期
    distribute: Boolean //是否派发
end

rule "test1"
    when
        $pojo : TestPojo(name == "name1")
    then
        $pojo.setDistribute(true);
end

rule "test2"
    when
        $pojo : TestPojo(name == "name2")
    then
        $pojo.setDistribute(true);
end